### ISSUE TITLE
安居客爬虫遇到302重定向问题

### ISSUE THREAD

**Issue by ThereIsLight** [lihansunbai/Fang_Scrapy#1]
你好，最近我也在做一个房地产信息爬虫。在爬取安居客二手房的网页是遇到了**302重定向问题**，会把我想要爬取的页面重定向到验证码网页。
我已经将DOWNLOAD_DELAY，COOKIES_ENABLED，USER_AGENTS设置好，此外也购买了阿布云代理隧道（代理IP）。
在爬取链家二手房信息时，没有遇到任何问题，成功爬取1500+条信息，但是在爬取安居客二手房信息时，遇到了302重定向问题.
我想问问您之前遇到过这个问题吗？有时如何解决的？

**Comment by lihansunbai** [comment]
根据我的经验，首先爬虫速度不能太快。
第二，如果你被重定向了，那就打开网页输一次验证码验证。
我上次被重定向就是这么巧合的解除的

**Comment by ThereIsLight** [comment]
DOWNLOAD_DELAY已经设置为5了，重定向之后也打开网页输入验证码，但是再次运行还是会有重定向错误。

**Comment by lihansunbai** [comment]
能不能正常通过网页访问安居客，正常访问会不会被重定向？

**Comment by Eat-an-orange** [comment]
> 你好，最近我也在做一个房地产信息爬虫。在爬取安居客二手房的网页是遇到了**302重定向问题**，会把我想要爬取的页面重定向到验证码网页。
> 我已经将DOWNLOAD_DELAY，COOKIES_ENABLED，USER_AGENTS设置好，此外也购买了阿布云代理隧道（代理IP）。
> 在爬取链家二手房信息时，没有遇到任何问题，成功爬取1500+条信息，但是在爬取安居客二手房信息时，遇到了302重定向问题.
> 我想问问您之前遇到过这个问题吗？有时如何解决的？

遇到了相同的问题，最后怎么解决的呢？

**Comment by lihansunbai** [comment]
用被封的IP的主机，手动打开一个安居客的页面然后输入验证码，就可以绕过302重定向了。


当然，这是我16年时候遇到重定向的解决方法，现在能不能适用你还要试一试。
