### ISSUE TITLE
爬虫下来的数据存放在哪里？

### ISSUE THREAD

**Issue by Solwarda** [lihansunbai/Fang_Scrapy#2]

**Comment by lihansunbai** [comment]
每个网站爬虫文件夹下的xinfang,ershoufang,zufang文件

**Comment by Solwarda** [comment]
运行 scrapy crawl 项目名称 -o price.json；就会将文件保存到price.json

在 2017-08-16 21:04:23，"lihansunbai" <notifications@github.com> 写道：


Closed #2.
