### ISSUE TITLE
Spider for Lianjia is out of date

### ISSUE THREAD

**Issue by build2last** [lihansunbai/Fang_Scrapy#3]
## OUT OF DATE
The HTML structure of [Lianjia](http://sh.lianjia.com/) had changed meaning most code in the project doesn't work any more.

Not found pretty trick for spider coding yet. 

It used to be a good script but lost much value for lack of maintaining.

**Comment by lihansunbai** [comment]
说实话已经好久没有维护这段代码了
简单粗暴的解析了各个平台的网页，没有成熟的软件设计架构，好多功能都是半原始的转态
可能很长时间没空维护它了
如果你想要继续使用它，请你善待它，做一些修改，我想它能很好的坚持爬下去的
^-^
